# -*- coding: utf-8 -*-
"""Disease_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RrndXoJfLT8tO3kwa44Jlsqu7TQbgxTO
"""

# app.py

import streamlit as st
import pandas as pd
import pickle

# -----------------------------
# Load Model
# -----------------------------
model = pickle.load(open('heart_model.pkl', 'rb'))
scaler = pickle.load(open('scaler.pkl', 'rb'))

# -----------------------------
# Page Title
# -----------------------------
st.title("❤️ Heart Disease Prediction App")

st.write("Enter patient medical details to predict heart disease.")

# -----------------------------
# User Inputs
# -----------------------------

age = st.slider("Age", 20, 100, 50)

sex = st.selectbox(
    "Sex",
    [0, 1],
    format_func=lambda x: "Female" if x == 0 else "Male"
)

cp = st.selectbox(
    "Chest Pain Type (cp)",
    [0,1,2,3]
)

trestbps = st.slider("Resting Blood Pressure", 80, 200, 120)

chol = st.slider("Cholesterol", 100, 600, 200)

fbs = st.selectbox(
    "Fasting Blood Sugar > 120 mg/dl",
    [0,1],
    format_func=lambda x: "No" if x == 0 else "Yes"
)

restecg = st.selectbox(
    "Resting ECG",
    [0,1,2]
)

thalach = st.slider("Maximum Heart Rate", 60, 220, 150)

exang = st.selectbox(
    "Exercise Induced Angina",
    [0,1],
    format_func=lambda x: "No" if x == 0 else "Yes"
)

oldpeak = st.slider("Oldpeak", 0.0, 6.5, 1.0)

slope = st.selectbox(
    "Slope",
    [0,1,2]
)

ca = st.selectbox(
    "Number of Major Vessels (ca)",
    [0,1,2,3,4]
)

thal = st.selectbox(
    "Thal",
    [0,1,2,3]
)

# -----------------------------
# Prediction Button
# -----------------------------

if st.button("Predict"):

    input_data = pd.DataFrame({
        'age': [age],
        'sex': [sex],
        'cp': [cp],
        'trestbps': [trestbps],
        'chol': [chol],
        'fbs': [fbs],
        'restecg': [restecg],
        'thalach': [thalach],
        'exang': [exang],
        'oldpeak': [oldpeak],
        'slope': [slope],
        'ca': [ca],
        'thal': [thal]
    })

    prediction = model.predict(input_data)

    # -----------------------------
    # Output
    # -----------------------------

    if prediction[0] == 1:
        st.error("⚠️ Heart Disease Detected")
    else:
        st.success("✅ No Heart Disease Detected")

