# -*- coding: utf-8 -*-
"""Disease_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RrndXoJfLT8tO3kwa44Jlsqu7TQbgxTO
"""

import streamlit as st
import pandas as pd
import pickle

# Load model and scaler
model = pickle.load(open('heart_model.pkl', 'rb'))
scaler = pickle.load(open('scaler.pkl', 'rb'))

st.title("❤️ Heart Disease Prediction App")

# Inputs
age = st.slider("Age", 20, 100, 50)
sex = st.selectbox("Sex", [0,1])
cp = st.selectbox("Chest Pain Type", [0,1,2,3])
trestbps = st.slider("Resting Blood Pressure", 80, 200, 120)
chol = st.slider("Cholesterol", 100, 600, 200)
fbs = st.selectbox("Fasting Blood Sugar", [0,1])
restecg = st.selectbox("Resting ECG", [0,1,2])
thalach = st.slider("Maximum Heart Rate", 60, 220, 150)
exang = st.selectbox("Exercise Induced Angina", [0,1])
oldpeak = st.slider("Oldpeak", 0.0, 6.5, 1.0)
slope = st.selectbox("Slope", [0,1,2])
ca = st.selectbox("CA", [0,1,2,3,4])
thal = st.selectbox("Thal", [0,1,2,3])

# Prediction
if st.button("Predict"):

    input_data = pd.DataFrame({
        'age':[age],
        'sex':[sex],
        'cp':[cp],
        'trestbps':[trestbps],
        'chol':[chol],
        'fbs':[fbs],
        'restecg':[restecg],
        'thalach':[thalach],
        'exang':[exang],
        'oldpeak':[oldpeak],
        'slope':[slope],
        'ca':[ca],
        'thal':[thal]
    })

    # Scale input
    input_scaled = scaler.transform(input_data)

    # Predict
    prediction = model.predict(input_scaled)

    if prediction[0] == 1:
        st.error("⚠️ Heart Disease Detected")
    else:
        st.success("✅ No Heart Disease")

